# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: discounted
version: '0.0.0'
github: "goosetherumfoodle/discounted"
license: MIT
author: "Jesse Hanley"
maintainer: "Jesse Hanley"
# synopsis: A new Haskeleton package.
# description: discounted is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - yaml
  - bytestring
  source-dirs: library

executables:
  discounted:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - discounted
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  discounted-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - discounted
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  discounted-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - discounted
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
